name: Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Creating kind cluster 
      uses: helm/kind-action@v1.0.0-rc.1

    - name: Print cluster information
      run: |
        kubectl config view
        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -n kube-system
        helm version
        kubectl version

    - uses: actions/checkout@v2

    - name: Deploy an application
      run: |
        kubectl apply -f https://raw.githubusercontent.com/chaos-mesh/apps/master/ping-baidu/busybox-statefulset.yaml
        
    - name: Run chaos mesh action
      uses: WangXiangUSTC/chaos-mesh-actions@master
      env:
        CHAOS_KIND: NetworkChaos
        CHAOS_DURATION: 30
        APP_NAME: nginx

    - name: Verify
      run: |
        echo "do some verify"
        ping -c 10 baidu.com
        kubectl exec busybox-0 -n busybox -it -- ping -c 30 baidu.com
